# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xcL1ge4XfeS4j-QqMwRayFBsWe2E6eeO
"""

import numpy as np
import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

# ===============================
# CONFIG
# ===============================
SUBJECTS = ["Math", "Science", "English", "SST", "Hindi"]
np.random.seed(42)

st.set_page_config(page_title="AI Student Performance Analyzer", layout="wide")
st.title("📘 AI-Based Student Performance & Board Readiness System")

# ===============================
# DATA GENERATION
# ===============================
@st.cache_data
def generate_students(n=40):
    students = []
    for i in range(1, n + 1):
        base = np.random.randint(30, 50) if i % 10 == 0 else np.random.randint(50, 70)
        student = {"ID": i}

        student["Class9"] = {s: base + np.random.randint(-5, 5) for s in SUBJECTS}
        student["Term1"] = {s: base + np.random.randint(0, 10) for s in SUBJECTS}
        student["Term2"] = {s: base + np.random.randint(5, 15) for s in SUBJECTS}
        student["Term3"] = {s: base + np.random.randint(0, 25) for s in SUBJECTS}

        students.append(student)
    return students

# ===============================
# FEATURE FUNCTIONS
# ===============================
def avg(term): return np.mean(list(term.values()))
def learning_velocity(s): return avg(s["Term3"]) - avg(s["Class9"])
def consistency_variance(s):
    return np.var([avg(s[t]) for t in ["Class9", "Term1", "Term2", "Term3"]])
def confidence_index(s): return round(max(0, 100 - consistency_variance(s)), 2)

# ===============================
# DATASET FOR ML
# ===============================
def build_dataset(students):
    X, y = [], []
    for s in students:
        X.append([
            avg(s["Class9"]), avg(s["Term1"]), avg(s["Term2"]), avg(s["Term3"]),
            learning_velocity(s), consistency_variance(s)
        ])
        y.append(avg(s["Term3"]) + np.random.normal(0, 3))
    return np.array(X), np.array(y)

# ===============================
# ML MODEL
# ===============================
@st.cache_resource
def train_model(students):
    X, y = build_dataset(students)
    scaler = StandardScaler()
    Xs = scaler.fit_transform(X)
    model = LinearRegression()
    model.fit(Xs, y)
    return model, scaler

# ===============================
# PERFORMANCE LOGIC
# ===============================
def performance_band(score):
    if score < 60: return "Critical Risk"
    elif score < 70: return "At Risk"
    elif score < 80: return "Stable"
    elif score < 90: return "Strong"
    else: return "Exceptional"

# ===============================
# LOAD DATA & MODEL
# ===============================
students = generate_students()
model, scaler = train_model(students)
X, _ = build_dataset(students)
preds = model.predict(scaler.transform(X))

# ===============================
# TEACHER DASHBOARD
# ===============================
st.header("👩‍🏫 Teacher Dashboard")

rows = []
for s, p in zip(students, preds):
    vel = learning_velocity(s)
    conf = confidence_index(s)
    rows.append({
        "Student ID": s["ID"],
        "Predicted Score": round(p, 2),
        "Category": performance_band(p),
        "Learning Velocity": round(vel, 2),
        "Confidence Index": conf,
        "Needs Attention": "YES" if p < 70 else "NO"
    })

df = pd.DataFrame(rows).sort_values("Predicted Score")
st.dataframe(df, use_container_width=True)

# ===============================
# STUDENT REPORT
# ===============================
st.header("🎓 Student AI Performance Report")

sid = st.selectbox("Select Student ID", df["Student ID"].tolist())
student = next(s for s in students if s["ID"] == sid)
pred = df[df["Student ID"] == sid]["Predicted Score"].values[0]

col1, col2, col3 = st.columns(3)
col1.metric("Predicted Board Score", round(pred, 2))
col2.metric("Performance Band", performance_band(pred))
col3.metric("Confidence Index", confidence_index(student))

# ===============================
# VISUALS
# ===============================
st.subheader("📈 Academic Growth Trend")
terms = ["Class9", "Term1", "Term2", "Term3"]
values = [avg(student[t]) for t in terms]

fig1, ax1 = plt.subplots()
ax1.plot(terms, values, marker="o")
ax1.set_ylabel("Average Marks")
ax1.grid(True)
st.pyplot(fig1)

st.subheader("📊 Subject-wise Performance")
class_avg = {sub: np.mean([s["Term3"][sub] for s in students]) for sub in SUBJECTS}
student_marks = [student["Term3"][s] for s in SUBJECTS]
avg_marks = [class_avg[s] for s in SUBJECTS]

fig2, ax2 = plt.subplots()
ax2.bar(SUBJECTS, student_marks, alpha=0.7)
ax2.plot(SUBJECTS, avg_marks, marker="o")
ax2.set_ylabel("Marks")
st.pyplot(fig2)

st.success("✅ AI-generated insights help teachers prioritize intervention & improve board results")